### ISSUE TITLE
Renseignements

### ISSUE THREAD

**Issue by alx68** [nmaupu/yokis-hack#13]
Bonjour,

Petites questions:
Est ce que le hack peut être compatible avec mon jeedom ,ou je peut mettre un plugin qui lit les brokers mqtt?.
J'aimerai vraiment utilise ton hack je souhaite changer la domotique que j'ai en place qui est en cpl qui a une 10 années
je trouve les modules yokis très résistant de plus ils me permettraient de faire la même chose que j'ai ,sans tout changer (câblage).  
Est ce que c'est bien ce materiel qu'il faut:
https://www.amazon.fr/Hiletgo-Nodemcu-Development-Esp8266-Compatible/dp/B01IXBWH9Y/ref=sr_1_fkmr2_1?dchild=1&keywords=Mini+NodeMcu+avec+module+WLAN+ESP8266-12F+Lua&qid=1611745994&sr=8-1-fkmr2

https://www.amazon.fr/dp/B07P95X6HM/ref=cm_sw_r_cp_apa_fabc_lDX5Fb58A9SYT?_encoding=UTF8&psc=1
Merci de bien vouloir m'aider.

**Comment by nmaupu** [comment]
Salut, oui c'est le bon matériel.
Je ne connais pas Jeedom donc je ne sais pas.

**Comment by alx68** [comment]
Ok merci ,
Jeedom ,c'est un peu comme home assistant .
