### ISSUE TITLE
Compilation issue on Raspberry PI 3, python3.7

### ISSUE THREAD

**Issue by lecocotier** [nmaupu/yokis-hack#15]
Hi, trying to compile give the following issue on all targets (here is d1_mini):
`Processing d1_mini (platform: espressif8266; board: d1_mini; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (3.0.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.30000.210519 (3.0.0) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa 2.100200.0 (10.2.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <RF24> 1.4.0
|   |-- <SPI> 1.0
|-- <ESP8266WiFi> 1.0
|-- <PubSubClient> 2.8.0
|-- <TelnetSpy> 1.1.0+sha.46fb7ec
|   |-- <ESP8266WiFi> 1.0
|-- <RingBuf> 2.0.1
|-- <ESPAsyncTCP> 1.2.2
|-- <ESP Async WebServer> 1.2.3
|   |-- <ESPAsyncTCP> 1.2.2
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <Ticker> 1.0
|-- <LittleFS(esp8266)> 0.1.0
Building in release mode
Compiling .pio/build/d1_mini/src/RF/RF24_forked.cpp.o
Archiving .pio/build/d1_mini/libe14/libSPI.a
Indexing .pio/build/d1_mini/libe14/libSPI.a
Archiving .pio/build/d1_mini/libd69/libRF24.a
Indexing .pio/build/d1_mini/libd69/libRF24.a
Compiling .pio/build/d1_mini/lib46a/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pio/build/d1_mini/lib46a/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pio/build/d1_mini/lib46a/ESP8266WiFi/ESP8266WiFi.cpp.o
src/RF/RF24_forked.cpp: In member function 'void RF24_forked::beginTransaction()':
src/RF/RF24_forked.cpp:83:9: error: expected unqualified-id before '.' token
   83 |     _SPI.beginTransaction(SPISettings(RF24_SPI_SPEED, MSBFIRST, SPI_MODE0));
      |         ^
src/RF/RF24_forked.cpp: In member function 'void RF24_forked::endTransaction()':
src/RF/RF24_forked.cpp:93:9: error: expected unqualified-id before '.' token
   93 |     _SPI.endTransaction();
      |         ^
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::read_register(uint8_t, uint8_t*, uint8_t)':
src/RF/RF24_forked.cpp:128:18: error: expected primary-expression before '.' token
  128 |     status = _SPI.transfer(R_REGISTER | (REGISTER_MASK & reg));
      |                  ^
src/RF/RF24_forked.cpp:130:22: error: expected primary-expression before '.' token
  130 |         *buf++ = _SPI.transfer(0xff);
      |                      ^
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::read_register(uint8_t)':
src/RF/RF24_forked.cpp:160:9: error: expected unqualified-id before '.' token
  160 |     _SPI.transfer(R_REGISTER | (REGISTER_MASK & reg));
      |         ^
src/RF/RF24_forked.cpp:161:18: error: expected primary-expression before '.' token
  161 |     result = _SPI.transfer(0xff);
      |                  ^
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::write_register(uint8_t, const uint8_t*, uint8_t)':
src/RF/RF24_forked.cpp:189:18: error: expected primary-expression before '.' token
  189 |     status = _SPI.transfer(W_REGISTER | (REGISTER_MASK & reg));
      |                  ^
src/RF/RF24_forked.cpp:190:23: error: expected unqualified-id before '.' token
  190 |     while (len--) _SPI.transfer(*buf++);
      |                       ^
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::write_register(uint8_t, uint8_t)':
src/RF/RF24_forked.cpp:219:18: error: expected primary-expression before '.' token
  219 |     status = _SPI.transfer(W_REGISTER | (REGISTER_MASK & reg));
      |                  ^
src/RF/RF24_forked.cpp:220:9: error: expected unqualified-id before '.' token
  220 |     _SPI.transfer(value);
      |         ^
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::write_payload(const void*, uint8_t, uint8_t)':
src/RF/RF24_forked.cpp:260:18: error: expected primary-expression before '.' token
  260 |     status = _SPI.transfer(writeType);
      |                  ^
src/RF/RF24_forked.cpp:262:13: error: expected unqualified-id before '.' token
  262 |         _SPI.transfer(*current++);
      |             ^
src/RF/RF24_forked.cpp:265:13: error: expected unqualified-id before '.' token
  265 |         _SPI.transfer(0);
      |             ^
src/RF/RF24_forked.cpp:233:20: warning: unused variable 'current' [-Wunused-variable]
  233 |     const uint8_t* current = reinterpret_cast<const uint8_t*>(buf);
      |                    ^~~~~~~
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::read_payload(void*, uint8_t)':
src/RF/RF24_forked.cpp:315:18: error: expected primary-expression before '.' token
  315 |     status = _SPI.transfer(R_RX_PAYLOAD);
      |                  ^
src/RF/RF24_forked.cpp:317:26: error: expected primary-expression before '.' token
  317 |         *current++ = _SPI.transfer(0xFF);
      |                          ^
src/RF/RF24_forked.cpp:320:13: error: expected unqualified-id before '.' token
  320 |         _SPI.transfer(0xff);
      |             ^
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::spiTrans(uint8_t)':
src/RF/RF24_forked.cpp:343:18: error: expected primary-expression before '.' token
  343 |     status = _SPI.transfer(cmd);
      |                  ^
src/RF/RF24_forked.cpp: In member function 'bool RF24_forked::begin()':
src/RF/RF24_forked.cpp:645:9: error: expected unqualified-id before '.' token
  645 |     _SPI.begin();
      |         ^
src/RF/RF24_forked.cpp: In member function 'uint8_t RF24_forked::getDynamicPayloadSize()':
src/RF/RF24_forked.cpp:1092:9: error: expected unqualified-id before '.' token
 1092 |     _SPI.transfer(R_RX_PL_WID);
      |         ^
src/RF/RF24_forked.cpp:1093:18: error: expected primary-expression before '.' token
 1093 |     result = _SPI.transfer(0xff);
      |                  ^
src/RF/RF24_forked.cpp: In member function 'void RF24_forked::toggle_features()':
src/RF/RF24_forked.cpp:1261:9: error: expected unqualified-id before '.' token
 1261 |     _SPI.transfer(ACTIVATE);
      |         ^
src/RF/RF24_forked.cpp:1262:9: error: expected unqualified-id before '.' token
 1262 |     _SPI.transfer(0x73);
      |         ^
src/RF/RF24_forked.cpp: In member function 'void RF24_forked::writeAckPayload(uint8_t, const void*, uint8_t)':
src/RF/RF24_forked.cpp:1359:9: error: expected unqualified-id before '.' token
 1359 |     _SPI.transfer(W_ACK_PAYLOAD | (pipe & 0x07));
      |         ^
src/RF/RF24_forked.cpp:1361:28: error: expected unqualified-id before '.' token
 1361 |     while (data_len--) _SPI.transfer(*current++);
      |                            ^
src/RF/RF24_forked.cpp:1342:20: warning: unused variable 'current' [-Wunused-variable]
 1342 |     const uint8_t* current = reinterpret_cast<const uint8_t*>(buf);
      |                    ^~~~~~~
*** [.pio/build/d1_mini/src/RF/RF24_forked.cpp.o] Error 1
================================================================================================================= [FAILED] Took 13.68 seconds =================================================================================================================

Environment     Status    Duration
--------------  --------  ------------
megaatmega2560  FAILED    00:00:03.508
d1_mini_ota     FAILED    00:00:18.594
d1_mini         FAILED    00:00:13.685
============================================================================================================ 3 failed, 0 succeeded in 00:00:35.787 ============================================================================================================`

**Comment by nmaupu** [comment]
Hi, Platformio seems not to be correctly installed.
Why are you trying to compile anyway ?

**Comment by lecocotier** [comment]
Hi, ok, I don't get what is wrong with platformio.
I'm trying to use your firmware to drive MVR500ERP devices, but only toggle command drives the device properly over telnet (ON, OFF, PAUSE) does nothing.
In home assistant, device is shown as MTR2000ERX.
That's why I wanted to be able to compile and try to find out what is wrong.

**Comment by lecocotier** [comment]
Answering myself.
I tried to build on another computer, same issue, it's maybe missing references to _SPI ?
To solve my shutter issue, I removed the configuration and imported it again replacing 0002 at the end of the line by 0003, there it's now a SHUTTER in the configuration and appears to work.

**Comment by lecocotier** [comment]
Issue solved, it's coming with last RF24 library v1.4.0 released some days ago.

Fixed by replacing in platformio.ini:
> lib_deps =
  RF24
by

> lib_deps =
  nrf24/RF24@1.3.11
