### ISSUE TITLE
Câblage d'un NodeMCU Amica v2

### ISSUE THREAD

**Issue by yakouzin** [nmaupu/yokis-hack#20]
Bonjour, 

Tout d'abord bravo et merci pour ce hack super utile, les modules Yokis étant très répandus et d'assez bonne qualité. Leur seul défaut à mes yeux est le fait que le protocole soit propriétaire et ton hack permet de remédier à cela.

Je suis un n00b total en électronique mais j'ai lu attentivement les instructions et les échanges avec d'autres personnes, du coup je pense avoir compris et je me sens capable de mettre ton hack en application. Cependant, j'avais commandé un D1 mini mais quand j'ai vu la taille des pins à souder... Je n'ai pas de fer suffisamment petit pour faire cela. Plutôt que d'acheter un fer adapté, il était largement plus économique de commandé un NodeMCU LUA Amica v2 qui a l'avantage d'avoir des pins déjà soudé.
J'ai étudié le schéma de la carte : 
![image](https://user-images.githubusercontent.com/98022367/150115354-4533b93a-8895-46e7-ab79-cd7b4b2e1f22.png)
et selon tes instructions j'en déduis que le câblage correct à réaliser entre le NodeMCU et le NRF24L01 est celui-ci : 

NRF24L01----NodeMCU
CLK-----------CLK
MOSI---------SD1
MISO---------SD0
CE------------D2
CS------------D8
IRQ-----------D1

Du coup j'ai trois questions : 

1/ peux-tu me confirmer que je peux bien utiliser mon NodeMCU?
2/ le câblage proposé ci-dessus est-il correct?
3/ concernant l'alimentation du NRF24L01, dois-je passer par un adaptateur 3,3V comme tu le décris, alimenté en 5V via le pin Vin du NodeMCU (qui est en 5V et, j'imagine, reliée au 5V du port USB?) ? OU puis-je alimenter directement le NRF24L01 par l'un des pins 3V3 du NodeMCU?

Merci

**Comment by nmaupu** [comment]
> 1/ peux-tu me confirmer que je peux bien utiliser mon NodeMCU?
oui

> 2/ le câblage proposé ci-dessus est-il correct?
oui, ça a l'air

> 3/ concernant l'alimentation du NRF24L01, dois-je passer par un adaptateur 3,3V comme tu le décris, alimenté en 5V via le pin Vin du NodeMCU (qui est en 5V et, j'imagine, reliée au 5V du port USB?) ? OU puis-je alimenter directement le NRF24L01 par l'un des pins 3V3 du NodeMCU?

Tu peux alimenter via le 3.3V de la carte si celui-ci est assez stable :man_shrugging: 
Surtout pas de 5V par contre !

**Comment by yakouzin** [comment]
Merci pour tes réponses rapides!

Pour la question 3 je me rend compte en lisant ta réponse que je me suis mal exprimé : 
Je veux dire : alimenter un **adaptateur** (j'ai celui-ci : https://www.amazon.fr/gp/product/B086V39YZS/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) par le pin Vin du NodeMCU et alimenter ensuite le NRF24L01 via l'adaptateur qui délivre un 3,3V bien stable.
C'est ce que tu as fait avec ton D1 mini si j'ai bien compris.
En fait ma question porte sur le fait que les pins ne portent pas tout à fait le même nom sur le D1 mini et le NodeMCU et donc je ne suis pas certain que je peux utiliser le pin Vin sur NodeMCU comme tu as utilisé le pin 5V du D1 mini. Pour moi c'est la même chose et c'est juste un pin qui récupère le 5V du port USB mais la différence de dénomination (combiné à ma n00bitude) me fait douter.
J'espère être plus clair.

J'ai pas mal regardé pour les fers, oui. jJe suis conscient du prix, mais je ne suis pas sûr qu'un fer de ce type me resservirait, je ne fais quasiment pas d'électronique et j'en ai déjà un adapté à ce dont j'ai habituellement besoin (mais trop gros/trop chaud pour souder sur un petit circuit). + il m'aurait fallu acheter du fil d'étain adapté également. Bref j'ai hésité mais j'ai finalement opté pour la solution du feignant (j'avoue).

**Comment by nmaupu** [comment]
Non, `Vin` n'est pas fait pour ça.
Le NodeMCU ne sort du 3.3V. Tu peux donc directement relier le NRF à un des 3.3V de la carte. Tu peux aussi passer par ton adaptateur qui doit aussi pouvoir être alimenté en 3.3V...

**Comment by yakouzin** [comment]
OK, du coup j'ai bien fait de poser la question.
En fait je me posais la question précisément parce que j'ai lu sur la spéc de l'adaptateur qu'il accepte en entrée une tension entre 4,8V et 12V donc 3,3V ça me paraît un poil faible. 
Reste la possibilité d'alimenter le NRF24L01 directement via le pin 3V3 du NodeMCU mais comme tu l'as souligné plus haut, il faut que le 3,3V fourni soit assez stable et je n'ai pas les moyens de le vérifier (ah ces n00b qui veulent se mettre à l’électronique mais n'ont pas de fer ni de multi).
En tout cas je vais arrêter les investigations sur cette solution pour l'instant parce qu'entre-temps j'ai sorti mon fer trop gros trop chaud et j'ai finalement tenter de faire les soudures avec. Je pense avoir réussi à souder les pins correctement sur le D1 mini, sans rien faire cramer.
Nos échanges ici devraient néanmoins pouvoir éventuellement servir à quelqu'un qui serait intéressé pour réaliser le montage avec autre chose qu'un D1 mini. Et puis j'y reviendrai peut-être si j'ai foiré mes soudures.
Bref, je n'ai plus qu'à entrer dans le vif du sujet pour faire marcher tout ça maintenant.
Merci pour ton aide.
