### ISSUE TITLE
home assistant discovery ne marche plus depuis la 2022.2 ?

### ISSUE THREAD

**Issue by steve41200** [nmaupu/yokis-hack#21]
Bonjour, je viens de faire la MAJ de homassistant 2022.2 et mes lumières Yokis remontent en indisponible.

J'ai testé je les pilotes toujours bien directement en ligne de commande sur l'esp, et je les commande aussi bien par MQTT.

dans les breaking change de la MAJ je vois ca 
The MQTT lights no longer support, the previously deprecated, value_template;state_value_template should be used instead.
Cela pourrait il avoir un lien ?
En regardant dans les details MQTT il lit ca
lot cuisine (light.ilot_cuisine) 
MQTT discovery data:
Topic: homeassistant/light/ilot/config
Payload
name: ilot switch
optimistic: 'false'
command_topic: ilot/cmnd/POWER
state_topic: ilot/tele/STATE
value_template: '{{value_json.POWER}}'
payload_off: 'OFF'
payload_on: 'ON'
availability_topic: ilot/tele/LWT
payload_available: Online
payload_not_available: Offline
unique_id: esp-ilot
device:
  name: ilot
  identifiers:
    - esp-ilot
  model: MTR2000ERX
  manufacturer: Yokis
platform: mqtt

et en effet il a un value_template qui doit etre un state_value_template maintenant a ce que je comprend

Je viens de revenir a la version 2021.12 et tout remarche.

As tu une idée de la marche a suivre pour rendre compatible avec la 2022.2 ?

**Comment by nmaupu** [comment]
Salut, pas encore testé la maj mais je dirais que tu as raison.
C'est cette ligne là je pense :
https://github.com/nmaupu/yokis-hack/blob/master/src/net/mqttHass.cpp#L68

Pas sûr qu'il faille juste changer de value_template à state_value_template... Il va falloir que je fasse des tests avant... Font chier quand même à tout casser tous les 4 matins...

**Comment by steve41200** [comment]
je viens de tester de créer a la main une light MQTT avec state_value_template et ca marche. 
Je te laisse faire les tests tiens moi au courant stp. Je pense que juste modifier cette ligne suffirait au feeling suivant mes petits tests

En attendant je reste en 2021.12 :)

**Comment by steve41200** [comment]
Je viens de détester en créant une lumière a la main en MQTT, et en changeant juste value par state value ca marche.
Je te met ce que j'ai mis dans mon fichier yaml.
`  - platform: mqtt
    name: ilot_test
    optimistic: false
    command_topic: "ilot/cmnd/POWER"
    state_topic: "ilot/tele/STATE"
    state_value_template: '{{value_json.POWER}}'
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "ilot/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false `

**Comment by steve41200** [comment]
salut je viens de la tester. Tout semble Ok en 2022.2 merci bcp :)
