### ISSUE TITLE
Discovery pour Home assistant 2023.8  semble changer

### ISSUE THREAD

**Issue by steve41200** [nmaupu/yokis-hack#23]
Bonjour, petit message préventif.
Je n'ai pas encore fait la mise a jour d'aout mais visiblement des choses changent sur MQTT pour HA

voila le lien des breacking changes qui font toujours peur
https://www.home-assistant.io/blog/2023/08/02/release-20238/#breaking-changes

Et voici un lien qui en parle qui précise que pour Z2M le correctif viendra en septembre mais que pour les autres "providers" MQTT il faut fixer le problème que je n'ai pas compris.
https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099?fbclid=IwAR1WX41EdQf2PTvxQ7EnqPhXmq-sIH-FnqM8jNgM14QOQGlyYFLKHLy0VvA

Voila affaire à suivre :)
Ils sont chiant a changer des trucs qui marchent ...

Ca te parles Nicolas ? Tu as une idée de quoi corriger ?

Bonne journées/vacances

**Comment by nmaupu** [comment]
Merci pour les infos détaillées ! Pas sûr de bien comprendre encore le
changement non plus 🤔...
On dirait que ça a avoir avec le name de l'entité. À priori il ne faudrait
plus le fournir...
https://github.com/nmaupu/yokis-hack/blob/c876cd3e2a56de171a49c5d66bc662cedfa92443/src/net/mqttHass.cpp#L34
et
https://github.com/nmaupu/yokis-hack/blob/c876cd3e2a56de171a49c5d66bc662cedfa92443/src/net/mqttHass.cpp#L63

doivent être modifiées je suppose...

Je ne rentrerai que fin de mois, d'ici là, si quelqu'un a d'autres
infos/PR, je suis preneur !

Merci,
Nico

**Comment by steve41200** [comment]
dans le lien que je t'ai mis j'ai vu ce post qui explique un peu mieux je trouve



Are you referring to what you’d need to fix? If yes… if your discovery information (or yaml configuration) is…

mqtt:
  sensor:
  - device:
      name: Zooz ZEN04
    ...
    name: Zooz ZEN04 Power
will cause the warning where this will not (and it’s how you should configure it from now on)


mqtt:
  sensor:
  - device:
      name: Zooz ZEN04
    ...
    name: Power
Otherwise you’ll get duplicate names for your entities. e.g. Zooz ZEN04 Zooz ZEN04 Power. Currently, HA under the hood removes this duplicate name during the transition period while all the upstream systems catch up.

**Comment by steve41200** [comment]
Bonjour, as tu trouvé une solution au changement annoncé ?

**Comment by nmaupu** [comment]
Je n'ai pas encore eu le temps de m'y atteler. Cela dit, le changement est simple, il suffit d'enlever le name du device dans le json.

**Comment by steve41200** [comment]
Ok. Rien de catastrophique alors :)Quand tu auras fais la modif tu pourras stp le dire sur ce fil que l’info remonte direct stp ?Merci encore pour ton programme.J’avais cherché pleins de trucs avant et c’est de loin le plus fiable.Le 3 sept. 2023 à 14:19, Nicolas Maupu ***@***.***> a écrit :﻿
Je n'ai pas encore eu le temps de m'y atteler. Cela dit, le changement est simple, il suffit d'enlever le name du device dans le json.

**Comment by nmaupu** [comment]
Hey, je viens de faire la modif sur une branche. As-tu moyen de tester (je n'ai pas encore la bonne version de Home Assistant pour le moment) ?

https://github.com/nmaupu/yokis-hack/releases/download/v1.5-hass-device-name/firmware.bin

**Comment by steve41200** [comment]
Salut, je me suis motivé pour tester ce matin, mais en reprenant mes tutos je bloque des l'étape sur mon Mac pour identifier le port usb.
"ls -l /dev | grep usbserial" saisie en terminal ne m'affiche rien.
Pourtant j'ai bien branché le yokishack dessus (j'arrive a interagir via HA avec les lumière, il est donc bien alimenté)

J'ai pourtant deja changé le firmware et ca ne me bloquait pas.

**Comment by nmaupu** [comment]
Essaye de lister les devices /dev/tty* pour voir ce qu'il y a...

Le sam. 16 sept. 2023 à 10:22, steve41200 ***@***.***> a
écrit :

**Comment by steve41200** [comment]
Ça me met rien en usb. EtrangeJ’ai mangé mon créneau de geekerie je dois gérer les petits.J’essaierai de brancher un autre truc en usb dessus pour voir Le 16 sept. 2023 à 10:26, Nicolas Maupu ***@***.***> a écrit :﻿
Essaye de lister les devices /dev/tty* pour voir ce qu'il y a...



Le sam. 16 sept. 2023 à 10:22, steve41200 ***@***.***> a

écrit :

**Comment by steve41200** [comment]
Ok je me suis remis sur le yokishack. je ne sais pas pk je ne trouvai pas l'usb. J'en ai branché un autre qui marchait, ensuite j'ai refait le yokishack qui a bien voulu marcher ...

j'ai réussit a passer le nouveau firmware, j'ai du reparametrer ensuite wifi, mqtt ainsi que les devices (j'avais sauvé les lignes pour des FSrestore).
Ca remarche dans HA.
En regardant les logs je n'ai pas revu l'erreur des noms.
Affaire ç suivre mais ton firmware me semble résoudre le souci

merci :)

**Comment by nmaupu** [comment]
Cool 😎 Merci infiniement pour tes tests, je vais tester de mon côté avant
de mettre à jour home assistant pour voir si c'est rétro-compatible !

Le sam. 16 sept. 2023 à 12:35, steve41200 ***@***.***> a
écrit :

**Comment by nmaupu** [comment]
C'est bien ce qui me semblait, sur l'ancienne version du moins, ça casse tous les noms...
![DeepinScreenshot_select-area_20230916130037](https://github.com/nmaupu/yokis-hack/assets/421550/a07d9548-8fa3-4566-88b1-63cc0eba7701)

**Comment by steve41200** [comment]
Bonne indépendance de voir la retro compatibilité.
De mon coté tout fonctionne avec les memes noms d'entités dans HA
Je viens de recheck le journal d'HA 1heure plus tard, toujours pas de message d'erreur précédente

**Comment by nmaupu** [comment]
Fixed !
https://github.com/nmaupu/yokis-hack/releases/tag/v1.6
