### ISSUE TITLE
HOw to send a cmd with mqtt

### ISSUE THREAD

**Issue by TTHOMAS52** [nmaupu/yokis-hack#25]
Hello, I'm loking for send a command with mqqt

I can Use the terminal to open or close my shutter with   "toggle volet_parrent_on"
but with qmtt I don't now

**Comment by nmaupu** [comment]
Hi,

I would say you can send a payload on the following topic:
`volet_parrent_on/tele/STATE`

The payload would be:
```{
  "POWER": "on"
}```

or `power off` depending on what you want to do !

**Comment by TTHOMAS52** [comment]
thank's and great job for your plungins

**Comment by TTHOMAS52** [comment]
I use this fork https://github.com/lecocotier/yokis-hack

 for JEEDOM, the topic is                            volet_parrent_on/cmnd/POWER
and valeur is                                                "ON" or "OFF"
thanks

**Comment by nmaupu** [comment]
I wasn't aware of this fork. Would be nice to integrate those changes but it seems Lecocotier is not around anymore. Does he ?

**Comment by TTHOMAS52** [comment]
I don't know
I clean the esp memory, pair my shutter  and  it don't work any more 
will try again your proposition

**Comment by TTHOMAS52** [comment]
Je suis un boulet mdr

**Comment by TTHOMAS52** [comment]
rectification after reboot the esp, it's ok
