### ISSUE TITLE
Are new Yokis Zigbee products supported ?

### ISSUE THREAD

**Issue by kirianguiller** [nmaupu/yokis-hack#26]
Yokis released in late 2023 a new series of devices that are Zigbee compatible (the "[Gamme UP](https://www.urmetwithyokis.fr/actualites-yokis/logement-connecte/yokis-devient-urmet-with-yokis)"). I wanted to know if these products are supported in this yokis-hack repo ? I'm currently searching these devices Zigbee definitions if that can help getting more control and insight on it.

Thanks for your time reading this !

**Comment by nmaupu** [comment]
Hello,

No, not supported and cannot be with actually chip (NRF24).
I don't plan on making test in the near future...

Le mer. 24 janv. 2024 à 10:46, Kirian Guiller ***@***.***> a
écrit :

**Comment by kirianguiller** [comment]
Alright, thanks a lot for your clear and quick reply !
