### ISSUE TITLE
YOKIS - JEEDOM

### ISSUE THREAD

**Issue by alx68** [nmaupu/yokis-hack#6]
Hello
Would it be possible to integrate the language on the jeedom home automation platform, thanks to the yokis key which is used by energeasyconnect (rexel).
Thank you for your reply.

**Comment by nmaupu** [comment]
Hi, I didn't quite understand your request but I guess everything is possible as long as it's documented somewhere.
Nevertheless, I don't have the required hardware to make further test + I don't know jeedom :/
Feel free to open a PR though ;-)
